name: CI Cache Demo

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ✅ Cache step
      - name: prime-cache-543e9f7
        id: cache-step
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-543e9f7

      # ✅ Step to echo cache result
      - name: Echo cache result
        run: |
          if [ "${{ steps.cache-step.outputs.cache-hit }}" = "true" ]; then
            echo "Cache hit!"
          else
            echo "Cache miss!"
          fi

      # Example dependency install (Python)
      - name: Install dependencies
        run: |
          pip install -r requirements.txt || echo "No requirements file found"
