name: Email Action Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 22f3001891@ds.study.iitm.ac.in
        run: echo "Hello, world! Workflow executed successfully."
